ref #70362 Добавить метод асинхронной передачи статуса в апи транспорта
retailcrm/mg-transport-api-client-go pull request #69
Opened 2020-12-15 12:53 UTC by kovtun-retailcrm

2020-12-15 14:40 UTC, Neur0toxine requested changes
Кроме указанных в дискуссиях замечаний также нужно:
* Восстановить работу тестов в библиотеке.
* Написать тест для добавленного метода.

2020-12-15 14:40 UTC, Neur0toxine commented on v1/types.go
> +	MessageExternalID string `json:"external_message_id"`
Не стоит менять название параметра в структуре. Здесь `ExternalMessageID` отлично подойдёт.

2020-12-15 14:40 UTC, Neur0toxine commented on v1/types.go
> +	ChannelID         uint64 `json:"channel"`
Аналогично предыдущему - нужно указать просто `Channel`.

2020-12-15 14:40 UTC, Neur0toxine commented on v1/client.go
> +func (c *MgClient) AckMessage(request AckMessageRequest) (AckMessageResponse, int, error) {
Метод в API возвращает пустой объект при успехе. Нет смысла возвращать этот же объект из библиотеки - достаточно возвращать `int, error`.

2020-12-15 14:40 UTC, Neur0toxine commented on v1/types.go
> +type AckMessageResponse struct{}
Эту структуру можно не добавлять в библиотеку.

2020-12-15 14:40 UTC, Neur0toxine commented on v1/client.go
> +//	fmt.Printf("%v %v\n", status, data)
Пример стоит указать в соответствии с методом `ActivateTransportChannel`.

2020-12-21 11:57 UTC, linniksa commented on v1/types.go
> +	Channel           uint64 `json:"channel"`
тут можно и ошибку передать

2020-12-21 11:59 UTC, linniksa requested changes

2020-12-21 11:59 UTC, linniksa commented on v1/types.go
> +	CustomerNotExistsError ErrorType = "customer_not_exists"
можно только у первой указывать тип

2020-12-21 11:59 UTC, linniksa commented on v1/types.go
> +type WebhookResponseError struct {
стоит переименовать в MessageSentError

2020-12-21 12:06 UTC, Neur0toxine reviewed
Ревью от @linniksa исчерпывающее; дополнительно ничего добавить не могу. К тестам нет претензий т.к. переменные окружения не пробрасываются, необходимость добавления теста для метода озвучена ранее.

2020-12-23 08:54 UTC, merged